version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1012123
      - MYSQL_DATABASE=construction_company
    ports:
      - '3307:3306'

  construction_app:
    container_name: construction_company
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/construction_company?useSSL=false&allowPublicKeyRetrieval=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "1012123",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    depends_on:
      - mysql-db