spring:
  datasource:
    url: jdbc:mysql://localhost:3306/construction_company
    username: root
    password: 101212
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
